# This is the linting configuration for Azure Pipelines
# You should not need to change this unelss you have an
# application which is incompatible with the version of
# Python we are using, in which case your config should
#Â be changed to use another version (see comment below)
#
# You may also have to change the Python version inside
# the Pipfile (set python_version to different version)

jobs:
- job: lint
  displayName: "Lint"

  pool:
    vmImage: 'Ubuntu 16.04'

  variables:
    PIPENV_CACHE_DIR: ".cache/pipenv"
    PIP_CACHE_DIR: ".cache/pip"

  steps:
  - task: UsePythonVersion@0
    displayName: 'Set Python version'
    inputs:
      versionSpec: '3.7.x' # If your application does not support 3.7, change this
      addToPath: true

  - script: sudo pip3 install setuptools
    displayName: 'Install base dependencies'

  - script: sudo pip3 install pipenv
    displayName: 'Install Pipenv'

  - script: pipenv install --dev
    displayName: 'Install project dependencies'

  - script: pipenv run lint
    displayName: 'Lint the project'
